<?php

declare( strict_types=1 );

use Composer\IO\NullIO;
use Render\Autoloader\Attributes\AutoRunPlugin;

function fileFixtureRoot (): string
{
	return dirname( __DIR__ ) . '/Fixtures/e2e/AutoloadPlugin/basic-project';
}

function fileVendorDir (): string
{
	return fileFixtureRoot() . '/vendor';
}

function fileCleanupGeneratedFiles (): void
{
	$vendorDir = fileVendorDir();

	if ( !is_dir( $vendorDir ) ) {
		return;
	}

	$iterator = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $vendorDir, RecursiveDirectoryIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::CHILD_FIRST,
	);

	foreach ( $iterator as $item ) {
		$item->isDir()
			? rmdir( $item->getPathname() )
			: unlink( $item->getPathname() );
	}

	rmdir( $vendorDir );
}

function runAutoRunPlugin ( array $config ): array
{
	$path = ( new AutoRunPlugin( new NullIO(), fileVendorDir() ) )->run( [
		'autoload-by-attr' => $config,
	] );

	return [
		'path'    => $path,
		'content' => $path ? file_get_contents( $path ) : NULL,
	];
}

function fileDirectRunAutoRunPlugin ( array $extra ): array
{
	$composerJson = fileFixtureRoot() . '/composer.json';

	file_put_contents( $composerJson, json_encode( [
		'config' => [ 'vendor-dir' => 'vendor' ],
		'extra'  => $extra,
	], JSON_PRETTY_PRINT ) );

	try {
		$path = AutoRunPlugin::directRun( $composerJson );
	}
	finally {
		@unlink( $composerJson );
	}

	return [
		'path'    => $path,
		'content' => $path ? file_get_contents( $path ) : NULL,
	];
}

function fileRuntimeAutoRunPlugin ( string|array $config ): array
{
	$path = AutoRunPlugin::runtime( fileVendorDir(), $config );

	return [
		'path'    => $path,
		'content' => $path ? file_get_contents( $path ) : NULL,
	];
}

function fileNormalizeBootstrap ( string $content ): string
{
	$content = str_replace( "\r\n", "\n", $content );
	$content = str_replace( str_replace( '\\', '/', fileFixtureRoot() ), '<fixture-root>', $content );
	$content = preg_replace( '/Generated: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/', 'Generated: <timestamp>', $content );
	$content = preg_replace( "/\n\/\/ Auto-generated by AutoloadPlugin - do not edit\n\/\/ Generated: [^\n]+\n/", '', $content );

	return rtrim( $content ) . "\n";
}

function fileExpectedBootstrap ( string $file ): string
{
	$content = file_get_contents( fileFixtureRoot() . '/expected/' . $file );

	return fileNormalizeBootstrap( $content );
}

beforeEach( function () {
	fileCleanupGeneratedFiles();
} );

afterEach( function () {
	fileCleanupGeneratedFiles();
} );

describe( 'AutoRunPlugin e2e', function () {

	it( 'generates the expected bootstrap file', function ( array $config, string $outputFile, string $expectedFile ) {
		$result = runAutoRunPlugin( $config );

		$result['path'] = str_replace( '\\', '/', $result['path'] );

		expect( $result['path'] )->toBe( str_replace( '\\', '/', fileVendorDir() . '/composer/' . $outputFile ) );
		expect( $result['path'] )->toBeFile();
		expect( $result['content'] )->toBeString();
		expect( fileNormalizeBootstrap( $result['content'] ) )->toBe( fileExpectedBootstrap( $expectedFile ) );
	} )->with( ( function () {
		$cases = [];

		foreach ( glob( fileFixtureRoot() . '/expected/*.json' ) ?: [] as $jsonFile ) {
			$name         = basename( $jsonFile, '.json' );
			$phpFile      = $name . '.php';
			$json         = json_decode( file_get_contents( $jsonFile ), TRUE, flags: JSON_THROW_ON_ERROR );
			$config       = $json['config'] ?? $json;
			$output       = $config['output'] ?? 'autoload_bootstrap.php';
			$cases[$name] = [ $config, $output, $phpFile ];
		}

		return $cases;
	} )() );

	it( 'returns null when no matching entries are found', function ( array $config ) {
		$result = runAutoRunPlugin( $config );

		expect( $result['path'] )->toBeNull();
		expect( $result['content'] )->toBeNull();
		expect( glob( fileVendorDir() . '/composer/e2e-*.php' ) ?: [] )->toBeEmpty();
	} )->with( [
		'missing directory' => [
			[
				'attribute' => 'AutoRun',
				'patterns'  => [ 'missing' ],
				'output'    => 'e2e-missing.php',
			],
		],
		'wrong attribute'   => [
			[
				'attribute' => 'OtherAttribute',
				'patterns'  => [ 'src' ],
				'output'    => 'e2e-wrong-attribute.php',
			],
		],
	] );

	it( 'removes stale output when no matching entries are found', function () {
		$output = fileVendorDir() . '/composer/e2e-stale.php';

		mkdir( dirname( $output ), recursive: TRUE );
		file_put_contents( $output, '<?php // stale' );

		$result = runAutoRunPlugin( [
			'attribute' => 'AutoRun',
			'patterns'  => [ 'missing' ],
			'output'    => 'e2e-stale.php',
		] );

		expect( $result['path'] )->toBeNull();
		expect( $output )->not->toBeFile();
	} );

} );

describe( 'AutoRunPlugin::directRun e2e', function () {

	it( 'generates the expected bootstrap file via directRun', function ( array $config, string $outputFile, string $expectedFile ) {
		$result = fileDirectRunAutoRunPlugin( [ 'autoload-by-attr' => $config ] );

		$result['path'] = str_replace( '\\', '/', $result['path'] );

		expect( $result['path'] )->toBe( str_replace( '\\', '/', fileVendorDir() . '/composer/' . $outputFile ) );
		expect( $result['path'] )->toBeFile();
		expect( $result['content'] )->toBeString();
		expect( fileNormalizeBootstrap( $result['content'] ) )->toBe( fileExpectedBootstrap( $expectedFile ) );
	} )->with( ( function () {
		$cases = [];

		foreach ( glob( fileFixtureRoot() . '/expected/*.json' ) ?: [] as $jsonFile ) {
			$name         = basename( $jsonFile, '.json' );
			$phpFile      = $name . '.php';
			$json         = json_decode( file_get_contents( $jsonFile ), TRUE, flags: JSON_THROW_ON_ERROR );
			$config       = $json['config'] ?? $json;
			$output       = $config['output'] ?? 'autoload_bootstrap.php';
			$cases[$name] = [ $config, $output, $phpFile ];
		}

		return $cases;
	} )() );

	it( 'returns null when no matching entries are found via directRun', function ( array $config ) {
		$result = fileDirectRunAutoRunPlugin( [ 'autoload-by-attr' => $config ] );

		expect( $result['path'] )->toBeNull();
		expect( $result['content'] )->toBeNull();
		expect( glob( fileVendorDir() . '/composer/e2e-*.php' ) ?: [] )->toBeEmpty();
	} )->with( [
		'missing directory' => [
			[
				'attribute' => 'AutoRun',
				'patterns'  => [ 'missing' ],
				'output'    => 'e2e-missing.php',
			],
		],
		'wrong attribute'   => [
			[
				'attribute' => 'OtherAttribute',
				'patterns'  => [ 'src' ],
				'output'    => 'e2e-wrong-attribute.php',
			],
		],
	] );

	it( 'returns null when extra key is missing via directRun', function () {
		$result = fileDirectRunAutoRunPlugin( [] );

		expect( $result['path'] )->toBeNull();
	} );

	it( 'throws when composer.json is missing', function () {
		AutoRunPlugin::directRun( fileFixtureRoot() . '/missing-composer.json' );
	} )->throws( InvalidArgumentException::class, 'composer.json not found' );

	it( 'throws when composer.json is invalid JSON', function () {
		$composerJson = fileFixtureRoot() . '/composer.json';
		file_put_contents( $composerJson, 'not json {' );

		try {
			AutoRunPlugin::directRun( $composerJson );
		}
		finally {
			@unlink( $composerJson );
		}
	} )->throws( InvalidArgumentException::class, 'Invalid composer.json' );

} );

describe( 'AutoRunPlugin::runtime e2e', function () {

	it( 'generates the expected bootstrap file via runtime', function ( array $config, string $outputFile, string $expectedFile ) {
		$config['force'] = TRUE;
		$result          = fileRuntimeAutoRunPlugin( $config );

		$result['path'] = str_replace( '\\', '/', $result['path'] );

		expect( $result['path'] )->toBe( str_replace( '\\', '/', fileVendorDir() . '/composer/' . $outputFile ) );
		expect( $result['path'] )->toBeFile();
		expect( $result['content'] )->toBeString();
		$actualContent = fileNormalizeBootstrap( $result['content'] );
		$actualContent = str_replace( [
			"\Demo\EdgeCases\Visibility::protectedMethod();\n", // protected method is not autoloaded
			"\Demo\EdgeCases\Visibility::privateMethod();\n", // private method is not autoloaded
			"\Demo\EdgeCases\TraitWithAutoload::traitMethod();\n", // trait method is not autoloaded
		], '', $actualContent );
		expect( $actualContent )->toBe( fileExpectedBootstrap( $expectedFile ) );
	} )->with( ( function () {
		$cases = [];

		foreach ( glob( fileFixtureRoot() . '/expected/*.json' ) ?: [] as $jsonFile ) {
			$name         = basename( $jsonFile, '.json' );
			$phpFile      = $name . '.php';
			$json         = json_decode( file_get_contents( $jsonFile ), TRUE, flags: JSON_THROW_ON_ERROR );
			$config       = $json['config'] ?? $json;
			$output       = $config['output'] ?? 'autoload_bootstrap.php';
			$cases[$name] = [ $config, $output, $phpFile ];
		}

		return $cases;
	} )() );

	it( 'skips regeneration when not stale', function () {
		$config = [
			'attribute' => 'AutoRun',
			'patterns'  => [ 'src' ],
			'output'    => 'e2e-stale-check.php',
			'force'     => TRUE,
		];
		fileRuntimeAutoRunPlugin( $config );

		$output = fileVendorDir() . '/composer/e2e-stale-check.php';
		$now    = time();
		touch( $output, $now );
		touch( fileFixtureRoot() . '/src/Example.php', $now - 100 );

		$config['force'] = FALSE;
		fileRuntimeAutoRunPlugin( $config );

		expect( filemtime( $output ) )->toBe( $now );
	} );

	it( 'regenerates when source file is newer', function () {
		$config = [
			'attribute' => 'AutoRun',
			'patterns'  => [ 'src' ],
			'output'    => 'e2e-stale-regen.php',
			'force'     => TRUE,
		];
		fileRuntimeAutoRunPlugin( $config );

		$output = fileVendorDir() . '/composer/e2e-stale-regen.php';
		$now    = time();
		touch( $output, $now - 100 );
		touch( fileFixtureRoot() . '/src/Example.php', $now );

		$config['force'] = FALSE;
		fileRuntimeAutoRunPlugin( $config );

		expect( filemtime( $output ) )->toBeGreaterThanOrEqual( $now );
	} );

	it( 'regenerates when cwf is a newer mtime integer', function () {
		$config = [
			'attribute' => 'AutoRun',
			'patterns'  => [ 'src' ],
			'output'    => 'e2e-stale-cwf-int.php',
			'force'     => TRUE,
		];
		fileRuntimeAutoRunPlugin( $config );

		$output = fileVendorDir() . '/composer/e2e-stale-cwf-int.php';
		$now    = time();
		touch( $output, $now - 100 );
		touch( fileFixtureRoot() . '/src/Example.php', $now - 200 );

		$config['force'] = FALSE;
		$config['cwf']   = $now;
		fileRuntimeAutoRunPlugin( $config );

		expect( filemtime( $output ) )->toBeGreaterThanOrEqual( $now );
	} );

	it( 'adds header and footer to generated bootstrap', function () {
		$result = fileRuntimeAutoRunPlugin( [
			'attribute' => 'AutoRun',
			'patterns'  => [ 'src' ],
			'output'    => 'e2e-output-header-footer.php',
			'header'    => [ "defined( 'ABSPATH' ) || exit;" ],
			'footer'    => [ "do_action( 'render_autoloader_loaded' );" ],
			'force'     => TRUE,
		] );

		$guardPos  = strpos( $result['content'], "defined( 'ABSPATH' ) || exit;" );
		$callPos   = strpos( $result['content'], '\\Demo\\Bootstrap::init();' );
		$footerPos = strpos( $result['content'], "do_action( 'render_autoloader_loaded' );" );

		expect( $result['content'] )->toContain( "defined( 'ABSPATH' ) || exit;" );
		expect( $result['content'] )->toContain( "do_action( 'render_autoloader_loaded' );" );
		expect( $guardPos )->toBeLessThan( $callPos );
		expect( $footerPos )->toBeGreaterThan( $callPos );
	} );

	it( 'writes empty bootstrap when cleanup=FALSE and no entries', function () {
		$output = fileVendorDir() . '/composer/e2e-cleanup-false.php';
		mkdir( dirname( $output ), recursive: TRUE );
		file_put_contents( $output, '<?php // existing' );

		$result = fileRuntimeAutoRunPlugin( [
			'attribute' => 'AutoRun',
			'patterns'  => [ 'missing' ],
			'output'    => 'e2e-cleanup-false.php',
			'cleanup'   => FALSE,
			'force'     => TRUE,
		] );

		expect( $output )->toBeFile();
		expect( $result['content'] )->not->toContain( 'existing' );
		expect( $result['content'] )->toContain( '<?php' );
	} );

	it( 'deletes output when cleanup=TRUE and no entries', function () {
		$output = fileVendorDir() . '/composer/e2e-cleanup-true.php';
		mkdir( dirname( $output ), recursive: TRUE );
		file_put_contents( $output, '<?php // existing' );

		$result = fileRuntimeAutoRunPlugin( [
			'attribute' => 'AutoRun',
			'patterns'  => [ 'missing' ],
			'output'    => 'e2e-cleanup-true.php',
			'cleanup'   => TRUE,
			'force'     => TRUE,
		] );

		expect( $result['path'] )->toBeNull();
		expect( $output )->not->toBeFile();
	} );

	it( 'throws when vendorDir is relative', function () {
		AutoRunPlugin::runtime( 'relative/path', [ 'patterns' => 'src' ] );
	} )->throws( InvalidArgumentException::class );

} );
