<?php

// Auto-generated by AutoloadPlugin - do not edit
// Generated: <timestamp>

require_once '<fixture-root>/src/functions.php';

\Demo\first_thing();
\Demo\Bootstrap::early();
\Demo\Bootstrap::init();
\Demo\middle_thing();
\Demo\Bootstrap::late();
