<?php

// Auto-generated by AutoloadPlugin - do not edit
// Generated: <timestamp>

require_once '<fixture-root>/src/functions.php';
require_once '<fixture-root>/src/EdgeCases/GlobalFunctions.php';

\Demo\EdgeCases\NegativePriority::veryEarly();
\Demo\EdgeCases\NegativePriority::earlyish();
\Demo\first_thing();
\Demo\Services\Logger::register();
\Demo\Bootstrap::early();
\Demo\EdgeCases\UnsafeWithAttrArgs::positional();
\Demo\EdgeCases\SamePriority::alpha();
\Demo\EdgeCases\SamePriority::beta();
\Demo\EdgeCases\SamePriority::gamma();
\Demo\EdgeCases\Visibility::publicMethod();
\Demo\EdgeCases\UnsafeFile::init();
\Demo\EdgeCases\UnsafeWithArrowFn::init();
\Demo\EdgeCases\UnsafeWithClassAttr::withAttr();
\Demo\EdgeCases\UnsafeWithAttrArgs::named();
\Demo\EdgeCases\UnsafeWithAnonFn::init();
\Demo\EdgeCases\SafeArrowFnTopLevel::init();
\global_init();
\global_setup();
\Demo\middle_thing();
\Demo\EdgeCases\ComplexSignatures::finalMethod();
\Demo\EdgeCases\ComplexSignatures::withReturnType();
\Demo\EdgeCases\ComplexSignatures::withParams();
\Demo\EdgeCases\ComplexSignatures::withNullable();
\Demo\EdgeCases\FalsePositives::actualMethod();
\Demo\EdgeCases\MultipleAttributes::withMultiple();
\Demo\EdgeCases\NonStaticMethods::staticMethod();
\Demo\Bootstrap::late();
\Demo\Bootstrap::init();
