<?php

// Auto-generated by AutoloadPlugin - do not edit
// Generated: <timestamp>

require_once '<project-dir>/.bootstrap.php';
require_once '<project-dir>/.git/hooks/pre-commit.php';
require_once '<project-dir>/UPPERCASE.PHP';
require_once '<project-dir>/build/compiled.php';
require_once '<project-dir>/cache/templates.php';
require_once '<project-dir>/config.php';
require_once '<project-dir>/inc/setup.php';
require_once '<project-dir>/inc/sub/extra.php';
require_once '<project-dir>/index.php';
require_once '<project-dir>/lib/Legacy.php';
require_once '<project-dir>/node_modules/wp-scripts/php/loader.php';
require_once '<project-dir>/src/.hidden.php';
require_once '<project-dir>/src/Admin/Settings.php';
require_once '<project-dir>/src/Admin/ajax-handler.php';
require_once '<project-dir>/src/Deep/Nested/Nested/File.php';
require_once '<project-dir>/src/Deep/Nested/Nested/Nested/File.php';
require_once '<project-dir>/src/Deep/Nested/Nested/Nested/Path/File.php';
require_once '<project-dir>/src/Excluded/debug.php';
require_once '<project-dir>/src/Helpers/arrays.inc.php';
require_once '<project-dir>/src/Helpers/functions.php';
require_once '<project-dir>/src/Plugin.php';
require_once '<project-dir>/src/bootstrap.php';
require_once '<project-dir>/tests/PluginTest.php';
require_once '<project-dir>/vendor/acme/utils/src/Helper.php';
