<?php

// Auto-generated by AutoloadPlugin - do not edit
// Generated: <timestamp>

require_once '<project-dir>/src/Deep/Nested/Nested/File.php';
require_once '<project-dir>/src/Deep/Nested/Nested/Nested/File.php';
require_once '<project-dir>/src/Deep/Nested/Nested/Nested/Path/File.php';
