<?php

// Auto-generated by AutoloadPlugin - do not edit
// Generated: <timestamp>

include '<project-dir>/inc/setup.php';
include '<project-dir>/inc/sub/extra.php';
include '<project-dir>/lib/Legacy.php';
include '<project-dir>/src/Deep/Nested/Nested/File.php';
include '<project-dir>/src/Deep/Nested/Nested/Nested/File.php';
include '<project-dir>/src/Deep/Nested/Nested/Nested/Path/File.php';
