<?php

// Auto-generated by AutoloadPlugin - do not edit
// Generated: <timestamp>

require_once '<project-dir>/.bootstrap.php';
require_once '<project-dir>/UPPERCASE.PHP';
require_once '<project-dir>/config.php';
require_once '<project-dir>/index.php';
