<?php

// Auto-generated by AutoloadPlugin - do not edit
// Generated: <timestamp>

require_once '<project-dir>/src/.hidden.php';
require_once '<project-dir>/src/Plugin.php';
require_once '<project-dir>/src/bootstrap.php';
