<?php

declare( strict_types=1 );

namespace Render\Autoloader;

class BootstrapRenderer
{
	/**
	 * Render complete bootstrap file content.
	 *
	 * @param Entry[]     $entries     Sorted entries to render
	 * @param string|null $generatedAt Timestamp for header (defaults to now)
	 *
	 * @return string Complete PHP file content
	 */
	public static function render ( array $entries, ?string $generatedAt = NULL ): string
	{
		$generatedAt ??= date( 'Y-m-d H:i:s' );

		$lines = [
			self::renderHeader( $generatedAt ),
			self::renderRequires( $entries ),
			self::renderCalls( $entries ),
		];

		return implode( "\n", array_filter( $lines ) ) . "\n";
	}

	/**
	 * Render file header with timestamp.
	 *
	 * @param string|null $generatedAt Timestamp (defaults to now)
	 *
	 * @return string PHP open tag and comment block
	 */
	public static function renderHeader ( ?string $generatedAt = NULL ): string
	{
		$generatedAt ??= date( 'Y-m-d H:i:s' );

		return <<<PHP
            <?php

            // Auto-generated by AutoloadPlugin - do not edit
            // Generated: {$generatedAt}
            PHP;
	}

	/**
	 * Render import statements for function files.
	 *
	 * Groups entries by file, determines winning import strategy,
	 * and wraps in function_exists check when needed.
	 *
	 * @param Entry[] $entries Entries to process
	 *
	 * @return string Import statements or empty string
	 */
	public static function renderRequires ( array $entries ): string
	{
		$grouped = self::groupEntriesByFile( $entries );

		if ( empty( $grouped ) ) {
			return '';
		}

		$lines = [];

		foreach ( $grouped as $file => $fileEntries ) {
			$line = self::renderFileImport( $file, $fileEntries );

			if ( $line !== '' ) {
				$lines[] = $line;
			}
		}

		return empty( $lines ) ? '' : "\n" . implode( "\n", $lines );
	}

	/**
	 * Group function entries by file path.
	 *
	 * @param Entry[] $entries All entries
	 *
	 * @return array<string, Entry[]> Entries grouped by file
	 */
	private static function groupEntriesByFile ( array $entries ): array
	{
		$grouped = [];

		foreach ( $entries as $entry ) {
			if ( $entry->needsRequire() ) {
				$grouped[$entry->file][] = $entry;
			}
		}

		return $grouped;
	}

	/**
	 * Render import statement for a single file.
	 *
	 * @param string  $file    File path
	 * @param Entry[] $entries Entries in this file
	 *
	 * @return string Import statement (may be wrapped in function_exists check)
	 */
	private static function renderFileImport ( string $file, array $entries ): string
	{
		$import = self::determineWinningImport( $entries );

		if ( $import === Import::None ) {
			return '';
		}

		$functionsToCheck = self::collectFunctionsToCheck( $entries );
		$escapedFile      = addslashes( str_replace( '\\', '/', $file ) );
		$importStatement  = "{$import->value} '{$escapedFile}';";

		if ( empty( $functionsToCheck ) ) {
			return $importStatement;
		}

		return self::wrapWithFunctionCheck( $importStatement, $functionsToCheck );
	}

	/**
	 * Determine winning import strategy for a file.
	 *
	 * Highest precedence wins: none > require_once > include_once > require > include
	 *
	 * @param Entry[] $entries Entries in the file
	 *
	 * @return Import Winning import strategy
	 */
	private static function determineWinningImport ( array $entries ): Import
	{
		return Import::highest( ...array_map( fn( $e ) => $e->import, $entries ) );
	}

	/**
	 * Collect function names that should be checked with function_exists.
	 *
	 * @param Entry[] $entries Entries in the file
	 *
	 * @return string[] Function names to check
	 */
	private static function collectFunctionsToCheck ( array $entries ): array
	{
		$functions = [];

		foreach ( $entries as $entry ) {
			if ( $entry->type === 'function' && $entry->check ) {
				$functions[] = $entry->class
					? $entry->class . '\\' . $entry->name
					: $entry->name;
			}
		}

		return $functions;
	}

	/**
	 * Wrap import statement with function_exists check.
	 *
	 * @param string   $importStatement The import statement
	 * @param string[] $functions       Functions to check
	 *
	 * @return string Wrapped statement
	 */
	private static function wrapWithFunctionCheck ( string $importStatement, array $functions ): string
	{
		$escaped = array_map( fn( $f ) => "'{$f}'", $functions );
		$list    = implode( ', ', $escaped );

		return "if (array_filter([{$list}], fn(\$f) => !function_exists(\$f))) {\n    {$importStatement}\n}";
	}

	/**
	 * Render all callable invocations.
	 *
	 * @param Entry[] $entries Entries to render
	 *
	 * @return string Call statements or empty string
	 */
	public static function renderCalls ( array $entries ): string
	{
		if ( empty( $entries ) ) {
			return '';
		}

		$lines = array_filter( array_map(
			fn( Entry $e ) => self::renderCall( $e ),
			$entries,
		) );

		if ( empty( $lines ) ) {
			return '';
		}

		return "\n" . implode( "\n", $lines );
	}

	/**
	 * Render single callable invocation.
	 *
	 * @param Entry $entry Entry to render
	 *
	 * @return string Call statement (e.g., "\App\Service::init();")
	 */
	public static function renderCall ( Entry $entry ): string
	{
		if ( empty( $callable = $entry->getCallable() ) ) {
			return '';
		}

		return $callable . '();';
	}
}
