<?php

declare( strict_types=1 );

use Render\Autoloader\BootstrapRenderer;

describe( 'BootstrapRenderer', function () {

	describe( 'renderHeader', function () {

		it( 'includes timestamp', function () {
			$header = BootstrapRenderer::renderHeader( '2024-01-01 12:00:00' );

			expect( $header )->toContain( '<?php' );
			expect( $header )->toContain( 'Auto-generated by AutoloadPlugin' );
			expect( $header )->toContain( '2024-01-01 12:00:00' );
		} );

	} );

	describe( 'renderCall', function () {

		it( 'renders callable format', function ( array $props, string $expected ) {
			$entry = makeEntry( $props );
			expect( BootstrapRenderer::renderCall( $entry ) )->toBe( $expected );
		} )->with( [
			'method'              => [
				[ 'type' => 'method', 'class' => 'App\\Service', 'name' => 'register' ],
				'\\App\\Service::register();',
			],
			'namespaced function' => [
				[ 'type' => 'function', 'class' => 'App\\Helpers', 'name' => 'bootstrap' ],
				'\\App\\Helpers\\bootstrap();',
			],
			'global function'     => [
				[ 'type' => 'function', 'class' => '', 'name' => 'bootstrap' ],
				'\\bootstrap();',
			],
		] );

	} );

	describe( 'renderRequires', function () {

		it( 'handles entry types', function ( array $entryProps, int $expectedCount ) {
			$entries = array_map( fn( $props ) => makeEntry( $props ), $entryProps );
			$result  = BootstrapRenderer::renderRequires( $entries );
			$count   = $expectedCount > 0 ? substr_count( $result, "require_once '" ) : 0;
			expect( $count )->toBe( $expectedCount );
		} )->with( [
			'methods only (no requires)' => [ [ [ 'type' => 'method' ] ], 0 ],
			'functions (deduped)'        => [
				[
					[ 'type' => 'function', 'file' => '/a.php', 'check' => false ],
					[ 'type' => 'function', 'file' => '/a.php', 'check' => false ],
					[ 'type' => 'function', 'file' => '/b.php', 'check' => false ],
				],
				2,
			],
		] );

		it( 'normalizes path separators', function () {
			$entries = [ makeEntry( [ 'type' => 'function', 'file' => 'C:\\path\\to\\file.php', 'check' => false ] ) ];
			$result  = BootstrapRenderer::renderRequires( $entries );
			expect( $result )->toContain( "require_once 'C:/path/to/file.php';" );
		} );

		it( 'wraps with function_exists check when check=true', function () {
			$entries = [ makeEntry( [ 'type' => 'function', 'name' => 'myFunc', 'file' => '/a.php', 'check' => true ] ) ];
			$result  = BootstrapRenderer::renderRequires( $entries );
			expect( $result )->toContain( 'function_exists' );
			expect( $result )->toContain( "'myFunc'" );
		} );

		it( 'skips import for import=none', function () {
			$entries = [ makeEntry( [ 'type' => 'function', 'file' => '/a.php', 'import' => 'none' ] ) ];
			$result  = BootstrapRenderer::renderRequires( $entries );
			expect( $result )->toBe( '' );
		} );

		it( 'picks highest precedence import for same file', function () {
			$entries = [
				makeEntry( [ 'type' => 'function', 'name' => 'a', 'file' => '/a.php', 'import' => 'include', 'check' => false ] ),
				makeEntry( [ 'type' => 'function', 'name' => 'b', 'file' => '/a.php', 'import' => 'require_once', 'check' => false ] ),
			];
			$result = BootstrapRenderer::renderRequires( $entries );
			expect( $result )->toContain( "require_once '/a.php';" );
			expect( $result )->not->toContain( 'include' );
		} );

	} );

	describe( 'render', function () {

		it( 'renders complete bootstrap file', function () {
			$entries = [ makeEntry( [ 'type' => 'method', 'class' => 'App\\Service', 'name' => 'init' ] ) ];
			$result  = BootstrapRenderer::render( $entries, '2024-01-01 12:00:00' );

			expect( $result )->toContain( '<?php' );
			expect( $result )->toContain( 'Auto-generated' );
			expect( $result )->toContain( '2024-01-01 12:00:00' );
			expect( $result )->toContain( '\\App\\Service::init();' );
		} );

		it( 'orders requires before calls', function () {
			$entries = [ makeEntry( [ 'type' => 'function', 'class' => NULL, 'name' => 'bootstrap', 'file' => '/funcs.php' ] ) ];
			$result  = BootstrapRenderer::render( $entries, '2024-01-01 12:00:00' );

			$requirePos = strpos( $result, 'require_once' );
			$callPos    = strpos( $result, '\\bootstrap();' );

			expect( $requirePos )->toBeLessThan( $callPos );
		} );

		it( 'renders empty file for no entries', function () {
			$result = BootstrapRenderer::render( [], '2024-01-01 12:00:00' );

			expect( $result )->toContain( '<?php' );
			expect( $result )->not->toContain( '::' );
			expect( $result )->not->toContain( 'require_once' );
		} );

	} );

} );
